/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import static commons.ComunicationMessages.START_TURN;
import static commons.ComunicationMessages.STOP_TURN;
import commons.NumberToColorMap;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.text.DefaultCaret;


/**
 *
 * @author leona
 */
public class GameBoard extends javax.swing.JFrame {
    private NumberToColorMap numberToColorMap = new NumberToColorMap();
    private FrameController frameController;
    private JLabel[][] myBoard = new JLabel[10][10];
    private JButton[][] enemyBoard = new JButton[10][10];
    private List<JButton> enabledButtonsBeforeTurn = new ArrayList();

    /**
     * Creates new form GameBoard
     */
    public GameBoard(FrameController frameController) {
        this.frameController = frameController;
        setStyle();
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new JScrollPane(jTextArea1);
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Battleship Game");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel56.setText("C");

        jLabel57.setText("D");

        jLabel41.setText("4");

        jLabel58.setText("E");

        jLabel42.setText("5");

        jLabel59.setText("F");

        jLabel43.setText("6");

        jLabel60.setText("G");

        jLabel34.setText("7");

        jLabel61.setText("H");

        jLabel35.setText("8");

        jLabel62.setText("I");

        jLabel36.setText("9");

        jLabel63.setText("J");

        jLabel37.setText("10");

        jLabel38.setText("1");

        jLabel44.setText("2");

        jLabel45.setText("3");

        jLabel24.setText("A");

        jLabel25.setText("B");

        jLabel46.setText("4");

        jLabel47.setText("5");

        jLabel26.setText("C");

        jLabel48.setText("6");

        jLabel27.setText("D");

        jLabel49.setText("7");

        jLabel28.setText("E");

        jLabel50.setText("8");

        jLabel29.setText("F");

        jLabel51.setText("9");

        jLabel30.setText("G");

        jLabel52.setText("10");

        jLabel31.setText("H");

        jLabel53.setText("1");

        jLabel32.setText("I");

        jLabel54.setText("A");

        jLabel33.setText("J");

        jLabel55.setText("B");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel39.setText("2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel40.setText("3");

        jLabel2.setText("Your Board");

        jLabel3.setText("Enemy Board");

        jLabel4.setText("Game Log");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(259, 259, 259)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(144, 144, 144))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel38)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel39)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel40)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel41)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel42)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel43)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel34)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel35)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel36)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel53)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel44)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel45)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel46)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel47)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel48)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel49)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel50)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel51)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel52)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel53)
                                .addComponent(jLabel46)
                                .addComponent(jLabel52))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel44)
                                        .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel38)
                                .addComponent(jLabel41)
                                .addComponent(jLabel37))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel39)
                                        .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel54)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel55)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel56)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel57)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel58)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel59)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel60)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel61)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel62)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel63))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel25)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel26)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel27)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel28)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel29)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel30)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel31)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel32)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel33)))
                        .addGap(9, 9, 9))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            this.frameController.getConnection().sendGiveUp();
            exitGame();
        } catch (Throwable ex) {
            Logger.getLogger(GameBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void setStyle() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GameBoard().setVisible(true);
//            }
//        });
//    }
    
    public void myInitComponents() {
        setMyBoard(jPanel1);
        fillMyBoard();
        boolean firstPlay = !(frameController.getConnection().getClientSideData().getPlayerId() == 2);
        setEnemyBoard(jPanel2, firstPlay);
        
        
        addLogMessage("Game started.");
        if(frameController.getConnection().getClientSideData().getPlayerId() == 1) {
            addLogMessage("You are player number: " + frameController.getConnection().getClientSideData().getPlayerId() + ". You go First.");
        }else addLogMessage("You are player number: " + frameController.getConnection().getClientSideData().getPlayerId() + ". You wait to play.");
        
    }
    

    
    public void setMyBoard(JPanel panel) {
        panel.setLayout(new GridLayout(10,10,0,0));
        for(int i = 0 ; i < 10 ; i++) {
            for(int j = 0 ; j < 10 ; j++) {   
                JLabel label = new JLabel();
                myBoard[i][j] = label;
                Dimension buttonSize = new Dimension(30,30); 
                label.setPreferredSize(buttonSize);
                label.setBorder(BorderFactory.createLineBorder(Color.white, 1));
                label.setBackground(Color.LIGHT_GRAY);
                label.setOpaque(true);
                panel.add(label);
            }
        }
    }
    
    public void setEnemyBoard(JPanel panel, boolean firstPlay) {
        panel.setLayout(new GridLayout(10,10,0,0));
        for(int i = 0 ; i < 10 ; i++) {
            for(int j = 0 ; j < 10 ; j++) {   
                JButton button = new JButton();
                button.setEnabled(firstPlay);
                enemyBoard[i][j] = button;
                Dimension buttonSize = new Dimension(30,30); 
                button.setPreferredSize(buttonSize);
                button.setBorder(BorderFactory.createLineBorder(Color.white, 1));
                button.setBackground(Color.LIGHT_GRAY);
                
                button.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        enabledButtonsBeforeTurn.add(button);
                        JButton clickedButton = (JButton) e.getSource();
                        int zOrder = panel.getComponentZOrder(clickedButton);
                        frameController.getConnection().createBombOrder(zOrder);
                    }
                });
                
                panel.add(button);
            }
        }
    }
    
    public void fillMyBoard() {
        int[][] myBoats = frameController.getConnection().getClientSideData().getMatriz();
        for(int i = 0 ; i < 10 ; i++) {
            for(int j = 0 ; j < 10 ; j++) {
                if(myBoats[i][j] > 0) {
                    myBoard[i][j].setBackground(numberToColorMap.getColor(myBoats[i][j]));
                }
            }
        }
    }
    
    public void addLogMessage(String message) {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        String logMessage = sdf.format(new Date()) + ": " + message + "\n";
        jTextArea1.append(logMessage);
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }
    
    public void setMissOnEnemy(int x, int y) {
        JLabel iconLabel = new JLabel(new ImageIcon("src/commons/img/sea.png"));
        iconLabel.setLayout(new FlowLayout(FlowLayout.CENTER));
        enemyBoard[x][y].setBorderPainted(false);
        enemyBoard[x][y].setContentAreaFilled(false);
        enemyBoard[x][y].setFocusPainted(false);
        enemyBoard[x][y].setOpaque(false);
        enemyBoard[x][y].setEnabled(false);
        enemyBoard[x][y].setLayout(new BorderLayout());
        enemyBoard[x][y].add(iconLabel);
    }
    
    public void setHitOnEnemy(int x, int y) {
        JLabel iconLabel = new JLabel(new ImageIcon("src/commons/img/flames.png"));
        iconLabel.setLayout(new FlowLayout(FlowLayout.CENTER));
        enemyBoard[x][y].setBorderPainted(false);
        enemyBoard[x][y].setContentAreaFilled(false);
        enemyBoard[x][y].setFocusPainted(false);
        enemyBoard[x][y].setOpaque(false);
        enemyBoard[x][y].setEnabled(false);
        enemyBoard[x][y].setLayout(new BorderLayout());
        enemyBoard[x][y].add(iconLabel);
    }
    
    public void blockTurn() {
        for(int i = 0 ; i < 10 ; i++) {
            for(int j = 0 ; j < 10 ; j++) {
                enemyBoard[i][j].setEnabled(false);
            }
        }
    }
    
    public void unblockTurn() {
        for(int i = 0 ; i < 10 ; i++) {
            for(int j = 0 ; j < 10 ; j++) {
                if(!enabledButtonsBeforeTurn.contains(enemyBoard[i][j])) {
                    enemyBoard[i][j].setEnabled(true);
                } 
            }
        }
    }
    
    public void setMissOnMine(int x, int y) {
        Icon icon = new ImageIcon("src/commons/img/sea.png");
        myBoard[x][y].setIcon(icon);
    }
    
    public void setHitOnMine(int x, int y) {
        Icon icon = new ImageIcon("src/commons/img/flames.png");
        myBoard[x][y].setIcon(icon);
    }
    
    public void showResult(String logMessage) {
        String[] opcoes = {"Confirm"};
        int escolha = JOptionPane.showOptionDialog(this, logMessage, "End of the game",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opcoes, opcoes[0]);

        if(escolha == 0  || escolha == -1) {
            this.frameController.newGame();
            this.dispose();
        }
    }
    
    public void exitGame() {
        ClientFrame newGame = new ClientFrame();
        newGame.setVisible(true);
        try {
            this.frameController.getConnection().sendDisconnectMessage();
        } catch (Throwable ex) {
            Logger.getLogger(GameBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
