/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import socketgame.client.ClientSideConnection;
import commons.NumberToColorMap;
import java.awt.Dimension;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import socketgame.client.ClientSideConnection;

/**
 *
 * @author leona
 */
public class GridBoats extends javax.swing.JFrame {
    private ClientSideConnection clientSideConnection;
    private FrameController frameController;
    private NumberToColorMap colorMap = new NumberToColorMap();
    private int[][] matriz = new int[10][10];// usar booleano
    private List<Integer> listaBarcos = new ArrayList<>(List.of(5, 4, 3, 2, 1));

    /**
     * Creates new form testegrid
     */
    public GridBoats(FrameController frameController) {
        setStyle();
        this.frameController = frameController;
        this.clientSideConnection = frameController.getConnection();
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Battleship Game");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Horizontal", "Vertical" }));

        jButton1.setText("Reset boats");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save boats");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Place your boats");

        jLabel40.setText("3");

        jLabel26.setText("C");

        jLabel41.setText("4");

        jLabel27.setText("D");

        jLabel42.setText("5");

        jLabel28.setText("E");

        jLabel43.setText("6");

        jLabel29.setText("F");

        jLabel34.setText("7");

        jLabel30.setText("G");

        jLabel35.setText("8");

        jLabel31.setText("H");

        jLabel36.setText("9");

        jLabel32.setText("I");

        jLabel37.setText("10");

        jLabel33.setText("J");

        jLabel38.setText("1");

        jLabel24.setText("A");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel25.setText("B");

        jLabel39.setText("2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel38)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel39)
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel40)
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel41)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel42)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel43)
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel34)
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel36)
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel37))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jButton2))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel38)
                                        .addComponent(jLabel41)
                                        .addComponent(jLabel37))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel39)
                                                .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel24)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel25)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel26)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel27)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel28)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel29)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel30)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel31)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel32)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel33)
                                .addGap(9, 9, 9))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void setStyle() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        resetMatriz();
        resetBarcos();
        clearGrid();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(listaBarcos.isEmpty()) {
            this.clientSideConnection.setBoats(matriz);
            frameController.getLobby().setVisible(true);
            this.clientSideConnection.setBoatsMessage(matriz);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Unused boats: Finish positioning your boats before starting", "Unused boats", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            this.frameController.getConnection().sendDisconnectMessage();
        } catch (Throwable ex) {
            Logger.getLogger(GridBoats.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void resetMatriz() {
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                this.matriz[i][j] = 0;
            }
        }
    }
    
    private void resetBarcos() {
        listaBarcos = new ArrayList<>(List.of(5, 4, 3, 2, 1));
    }
    
    private void clearGrid() {
        Component[] components = jPanel1.getComponents();
    
        for (Component component : components) {
            if (component instanceof JButton) {
                JButton button = (JButton) component;
                button.setBackground(Color.LIGHT_GRAY);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    
    //tornar funcao horizontal apenas e criar a vertical
    public boolean isDirectionValid(int x, int y, int zBarco, String direction) {
        if(direction == "Horizontal") {
            return x >= 0 && (x + zBarco - 1) < matriz.length && y >= 0 && y < matriz[0].length;
        }
        else if(direction == "Vertical") {
            return y >= 0 && (y + zBarco - 1) < matriz[0].length && x >= 0;     
        }
        return false;
    }
    
    public void setBarco(JButton actualButton, int zBarco, int x, int y, String direction) {
        int actualX = jPanel1.getComponentZOrder(actualButton);
        int nextX = actualX;
        
        if(direction == "Horizontal") {
            for(int i = x ; i < x + zBarco ; i++) {
                this.matriz[y][i] = zBarco;
            }

            actualButton.setBackground(colorMap.getColor(zBarco));
            
            for(int i = actualX ; i < (actualX + zBarco - 1) ; i++) {
                JButton nextButton = (JButton) jPanel1.getComponent(nextX + 1);
                nextX++;
                nextButton.setBackground(colorMap.getColor(zBarco));
            }
        }
        else if(direction == "Vertical") {
            for(int i = y; i < y + zBarco; i++) {
                this.matriz[i][x] = zBarco;
            }
            
            actualButton.setBackground(colorMap.getColor(zBarco));
            
            for(int i = actualX ; i < (actualX + zBarco - 1) ; i++) {
                JButton nextButton = (JButton) jPanel1.getComponent(nextX + 10);
                nextX = nextX + 10;
                nextButton.setBackground(colorMap.getColor(zBarco));
            }
        }
    }
    
    public boolean validateDirectionColision(int x, int y, int zBarco, String direction) {
        if(direction == "Horizontal") { 
            for(int i = x ; i < x + zBarco ; i++) {
                if(matriz[y][i] > 0) return false;
            }
            return true;
        }
        else if(direction == "Vertical") {
            for (int i = y; i < y + zBarco; i++) {
                if(matriz[i][x] > 0) return false;
            }
            return true;
        }
        return false;
    }
    
    private boolean validatePosition(int x, int y, int zBarco, String direction) {
        if(isDirectionValid(x, y, zBarco, direction) && validateDirectionColision(x, y, zBarco, direction)){
            return true;
        } 
        return false;
    }
    
    public void notifyFrame(String string) {
        System.out.println(string);
    }

    private void myInitComponents() {
        jPanel1.setLayout(new GridLayout(10,10,0,0));
        for(int i = 0 ; i < 10 ; i++) {
            for(int j = 0 ; j < 10 ; j++) {   
                JButton button = new JButton();
                Dimension buttonSize = new Dimension(30,30); 
                button.setPreferredSize(buttonSize);
                button.setBorder(BorderFactory.createLineBorder(Color.white, 1));
                button.setBackground(Color.LIGHT_GRAY);
                button.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        JButton clickedButton = (JButton) e.getSource();
                        String direction = jComboBox1.getSelectedItem().toString();
                        int x,y;
                        int column = jPanel1.getComponentZOrder(clickedButton);

                        if(column >= 0 && column <= 9) {
                            x = 0;
                            y = column;
                        }else {
                            x = column / 10;
                            y = column % 10;
                        }
                        
                        switch (direction) {
                            case "Horizontal":  
                                if (!listaBarcos.isEmpty() && validatePosition(y, x, listaBarcos.get(0), direction)) {
                                    setBarco(clickedButton, listaBarcos.get(0), y, x, direction);
                                    listaBarcos.remove(0);
                                } 
                            break;
                            
                            case "Vertical":
                                if (!listaBarcos.isEmpty() && validatePosition(y, x, listaBarcos.get(0), direction)) {
                                    setBarco(clickedButton, listaBarcos.get(0), y, x, direction);
                                    listaBarcos.remove(0);
                                }
                                break;
                        }
                    }
                });
                jPanel1.add(button);
            }
        }
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
